version: "3"
services: 
  app.test:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
      - GITLAB_USER="${GITLAB_USER}"
    image: ambienteeducativofront-1.0
    ports:
      - "${APP_PORT:-80}:80"
      #- "${APP_PORTHTTPS:-443}:443"
    volumes:
     - ".:/var/www/html"